logging:
  level:
    ROOT: INFO

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java.version: @java.version@

spring:
  application:
    name: spring-starter
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8090
  servlet:
    context-path: /api

jwt:
  token:
    secret: Mysecret
    refresh: 15 # Minutes
    expiration:
      web: 60 # Minutes
      app: 21600 # Minutes
      default: 60 # Minutes
